//! Unified Expressions shape indices, matching VRCFaceTracking `UnifiedExpressions`.
//!
//! Gaze, eyelid openness, and pupil size live on [`crate::VfEyeData`], not in this enum.
//! `Max` is the last discriminant and the exclusive end of the shapes array.

use core::fmt;

/// Number of slots in [`crate::VfUnifiedFrame::shapes`], including the unused `Max` slot.
pub const VF_UNIFIED_SHAPE_COUNT: usize = UnifiedExpression::Max as usize + 1;

/// Standard ARKit / PerfectSync blendshape count.
pub const ARKIT_BLENDSHAPE_COUNT: u32 = 52;
/// PICO native weight count (52 ARKit-like + 20 visemes).
pub const PICO_BLENDSHAPE_COUNT: u32 = 72;
/// ARKit viseme count packed after the 52 expression shapes on PICO.
pub const VISEME_COUNT: u32 = 20;

/// Anatomical Unified Expressions, in VRCFT order (C# enum starting at 0).
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum UnifiedExpression {
    EyeSquintRight = 0,
    EyeSquintLeft,
    EyeWideRight,
    EyeWideLeft,
    BrowPinchRight,
    BrowPinchLeft,
    BrowLowererRight,
    BrowLowererLeft,
    BrowInnerUpRight,
    BrowInnerUpLeft,
    BrowOuterUpRight,
    BrowOuterUpLeft,
    NasalDilationRight,
    NasalDilationLeft,
    NasalConstrictRight,
    NasalConstrictLeft,
    CheekSquintRight,
    CheekSquintLeft,
    CheekPuffRight,
    CheekPuffLeft,
    CheekSuckRight,
    CheekSuckLeft,
    JawOpen,
    JawRight,
    JawLeft,
    JawForward,
    JawBackward,
    JawClench,
    JawMandibleRaise,
    MouthClosed,
    LipSuckUpperRight,
    LipSuckUpperLeft,
    LipSuckLowerRight,
    LipSuckLowerLeft,
    LipSuckCornerRight,
    LipSuckCornerLeft,
    LipFunnelUpperRight,
    LipFunnelUpperLeft,
    LipFunnelLowerRight,
    LipFunnelLowerLeft,
    LipPuckerUpperRight,
    LipPuckerUpperLeft,
    LipPuckerLowerRight,
    LipPuckerLowerLeft,
    MouthUpperUpRight,
    MouthUpperUpLeft,
    MouthUpperDeepenRight,
    MouthUpperDeepenLeft,
    NoseSneerRight,
    NoseSneerLeft,
    MouthLowerDownRight,
    MouthLowerDownLeft,
    MouthUpperRight,
    MouthUpperLeft,
    MouthLowerRight,
    MouthLowerLeft,
    MouthCornerPullRight,
    MouthCornerPullLeft,
    MouthCornerSlantRight,
    MouthCornerSlantLeft,
    MouthFrownRight,
    MouthFrownLeft,
    MouthStretchRight,
    MouthStretchLeft,
    MouthDimpleRight,
    MouthDimpleLeft,
    MouthRaiserUpper,
    MouthRaiserLower,
    MouthPressRight,
    MouthPressLeft,
    MouthTightenerRight,
    MouthTightenerLeft,
    TongueOut,
    TongueUp,
    TongueDown,
    TongueRight,
    TongueLeft,
    TongueRoll,
    TongueBendDown,
    TongueCurlUp,
    TongueSquish,
    TongueFlat,
    TongueTwistRight,
    TongueTwistLeft,
    SoftPalateClose,
    ThroatSwallow,
    NeckFlexRight,
    NeckFlexLeft,
    Max,
}

impl UnifiedExpression {
    pub const ALL: [UnifiedExpression; 88] = [
        Self::EyeSquintRight,
        Self::EyeSquintLeft,
        Self::EyeWideRight,
        Self::EyeWideLeft,
        Self::BrowPinchRight,
        Self::BrowPinchLeft,
        Self::BrowLowererRight,
        Self::BrowLowererLeft,
        Self::BrowInnerUpRight,
        Self::BrowInnerUpLeft,
        Self::BrowOuterUpRight,
        Self::BrowOuterUpLeft,
        Self::NasalDilationRight,
        Self::NasalDilationLeft,
        Self::NasalConstrictRight,
        Self::NasalConstrictLeft,
        Self::CheekSquintRight,
        Self::CheekSquintLeft,
        Self::CheekPuffRight,
        Self::CheekPuffLeft,
        Self::CheekSuckRight,
        Self::CheekSuckLeft,
        Self::JawOpen,
        Self::JawRight,
        Self::JawLeft,
        Self::JawForward,
        Self::JawBackward,
        Self::JawClench,
        Self::JawMandibleRaise,
        Self::MouthClosed,
        Self::LipSuckUpperRight,
        Self::LipSuckUpperLeft,
        Self::LipSuckLowerRight,
        Self::LipSuckLowerLeft,
        Self::LipSuckCornerRight,
        Self::LipSuckCornerLeft,
        Self::LipFunnelUpperRight,
        Self::LipFunnelUpperLeft,
        Self::LipFunnelLowerRight,
        Self::LipFunnelLowerLeft,
        Self::LipPuckerUpperRight,
        Self::LipPuckerUpperLeft,
        Self::LipPuckerLowerRight,
        Self::LipPuckerLowerLeft,
        Self::MouthUpperUpRight,
        Self::MouthUpperUpLeft,
        Self::MouthUpperDeepenRight,
        Self::MouthUpperDeepenLeft,
        Self::NoseSneerRight,
        Self::NoseSneerLeft,
        Self::MouthLowerDownRight,
        Self::MouthLowerDownLeft,
        Self::MouthUpperRight,
        Self::MouthUpperLeft,
        Self::MouthLowerRight,
        Self::MouthLowerLeft,
        Self::MouthCornerPullRight,
        Self::MouthCornerPullLeft,
        Self::MouthCornerSlantRight,
        Self::MouthCornerSlantLeft,
        Self::MouthFrownRight,
        Self::MouthFrownLeft,
        Self::MouthStretchRight,
        Self::MouthStretchLeft,
        Self::MouthDimpleRight,
        Self::MouthDimpleLeft,
        Self::MouthRaiserUpper,
        Self::MouthRaiserLower,
        Self::MouthPressRight,
        Self::MouthPressLeft,
        Self::MouthTightenerRight,
        Self::MouthTightenerLeft,
        Self::TongueOut,
        Self::TongueUp,
        Self::TongueDown,
        Self::TongueRight,
        Self::TongueLeft,
        Self::TongueRoll,
        Self::TongueBendDown,
        Self::TongueCurlUp,
        Self::TongueSquish,
        Self::TongueFlat,
        Self::TongueTwistRight,
        Self::TongueTwistLeft,
        Self::SoftPalateClose,
        Self::ThroatSwallow,
        Self::NeckFlexRight,
        Self::NeckFlexLeft,
    ];

    pub const fn index(self) -> usize {
        self as usize
    }

    pub fn from_index(i: usize) -> Option<Self> {
        Self::ALL.get(i).copied()
    }

    pub fn from_name(name: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|e| e.name() == name)
    }

    pub const fn name(self) -> &'static str {
        match self {
            Self::EyeSquintRight => "EyeSquintRight",
            Self::EyeSquintLeft => "EyeSquintLeft",
            Self::EyeWideRight => "EyeWideRight",
            Self::EyeWideLeft => "EyeWideLeft",
            Self::BrowPinchRight => "BrowPinchRight",
            Self::BrowPinchLeft => "BrowPinchLeft",
            Self::BrowLowererRight => "BrowLowererRight",
            Self::BrowLowererLeft => "BrowLowererLeft",
            Self::BrowInnerUpRight => "BrowInnerUpRight",
            Self::BrowInnerUpLeft => "BrowInnerUpLeft",
            Self::BrowOuterUpRight => "BrowOuterUpRight",
            Self::BrowOuterUpLeft => "BrowOuterUpLeft",
            Self::NasalDilationRight => "NasalDilationRight",
            Self::NasalDilationLeft => "NasalDilationLeft",
            Self::NasalConstrictRight => "NasalConstrictRight",
            Self::NasalConstrictLeft => "NasalConstrictLeft",
            Self::CheekSquintRight => "CheekSquintRight",
            Self::CheekSquintLeft => "CheekSquintLeft",
            Self::CheekPuffRight => "CheekPuffRight",
            Self::CheekPuffLeft => "CheekPuffLeft",
            Self::CheekSuckRight => "CheekSuckRight",
            Self::CheekSuckLeft => "CheekSuckLeft",
            Self::JawOpen => "JawOpen",
            Self::JawRight => "JawRight",
            Self::JawLeft => "JawLeft",
            Self::JawForward => "JawForward",
            Self::JawBackward => "JawBackward",
            Self::JawClench => "JawClench",
            Self::JawMandibleRaise => "JawMandibleRaise",
            Self::MouthClosed => "MouthClosed",
            Self::LipSuckUpperRight => "LipSuckUpperRight",
            Self::LipSuckUpperLeft => "LipSuckUpperLeft",
            Self::LipSuckLowerRight => "LipSuckLowerRight",
            Self::LipSuckLowerLeft => "LipSuckLowerLeft",
            Self::LipSuckCornerRight => "LipSuckCornerRight",
            Self::LipSuckCornerLeft => "LipSuckCornerLeft",
            Self::LipFunnelUpperRight => "LipFunnelUpperRight",
            Self::LipFunnelUpperLeft => "LipFunnelUpperLeft",
            Self::LipFunnelLowerRight => "LipFunnelLowerRight",
            Self::LipFunnelLowerLeft => "LipFunnelLowerLeft",
            Self::LipPuckerUpperRight => "LipPuckerUpperRight",
            Self::LipPuckerUpperLeft => "LipPuckerUpperLeft",
            Self::LipPuckerLowerRight => "LipPuckerLowerRight",
            Self::LipPuckerLowerLeft => "LipPuckerLowerLeft",
            Self::MouthUpperUpRight => "MouthUpperUpRight",
            Self::MouthUpperUpLeft => "MouthUpperUpLeft",
            Self::MouthUpperDeepenRight => "MouthUpperDeepenRight",
            Self::MouthUpperDeepenLeft => "MouthUpperDeepenLeft",
            Self::NoseSneerRight => "NoseSneerRight",
            Self::NoseSneerLeft => "NoseSneerLeft",
            Self::MouthLowerDownRight => "MouthLowerDownRight",
            Self::MouthLowerDownLeft => "MouthLowerDownLeft",
            Self::MouthUpperRight => "MouthUpperRight",
            Self::MouthUpperLeft => "MouthUpperLeft",
            Self::MouthLowerRight => "MouthLowerRight",
            Self::MouthLowerLeft => "MouthLowerLeft",
            Self::MouthCornerPullRight => "MouthCornerPullRight",
            Self::MouthCornerPullLeft => "MouthCornerPullLeft",
            Self::MouthCornerSlantRight => "MouthCornerSlantRight",
            Self::MouthCornerSlantLeft => "MouthCornerSlantLeft",
            Self::MouthFrownRight => "MouthFrownRight",
            Self::MouthFrownLeft => "MouthFrownLeft",
            Self::MouthStretchRight => "MouthStretchRight",
            Self::MouthStretchLeft => "MouthStretchLeft",
            Self::MouthDimpleRight => "MouthDimpleRight",
            Self::MouthDimpleLeft => "MouthDimpleLeft",
            Self::MouthRaiserUpper => "MouthRaiserUpper",
            Self::MouthRaiserLower => "MouthRaiserLower",
            Self::MouthPressRight => "MouthPressRight",
            Self::MouthPressLeft => "MouthPressLeft",
            Self::MouthTightenerRight => "MouthTightenerRight",
            Self::MouthTightenerLeft => "MouthTightenerLeft",
            Self::TongueOut => "TongueOut",
            Self::TongueUp => "TongueUp",
            Self::TongueDown => "TongueDown",
            Self::TongueRight => "TongueRight",
            Self::TongueLeft => "TongueLeft",
            Self::TongueRoll => "TongueRoll",
            Self::TongueBendDown => "TongueBendDown",
            Self::TongueCurlUp => "TongueCurlUp",
            Self::TongueSquish => "TongueSquish",
            Self::TongueFlat => "TongueFlat",
            Self::TongueTwistRight => "TongueTwistRight",
            Self::TongueTwistLeft => "TongueTwistLeft",
            Self::SoftPalateClose => "SoftPalateClose",
            Self::ThroatSwallow => "ThroatSwallow",
            Self::NeckFlexRight => "NeckFlexRight",
            Self::NeckFlexLeft => "NeckFlexLeft",
            Self::Max => "Max",
        }
    }
}

impl fmt::Display for UnifiedExpression {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// Simplified blended shapes (VRCFT `UnifiedSimpleExpressions`).
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum UnifiedSimpleExpression {
    BrowUpRight = 0,
    BrowUpLeft,
    BrowDownRight,
    BrowDownLeft,
    MouthSmileRight,
    MouthSmileLeft,
    MouthSadRight,
    MouthSadLeft,
}

impl UnifiedSimpleExpression {
    pub const ALL: [Self; 8] = [
        Self::BrowUpRight,
        Self::BrowUpLeft,
        Self::BrowDownRight,
        Self::BrowDownLeft,
        Self::MouthSmileRight,
        Self::MouthSmileLeft,
        Self::MouthSadRight,
        Self::MouthSadLeft,
    ];

    pub const fn name(self) -> &'static str {
        match self {
            Self::BrowUpRight => "BrowUpRight",
            Self::BrowUpLeft => "BrowUpLeft",
            Self::BrowDownRight => "BrowDownRight",
            Self::BrowDownLeft => "BrowDownLeft",
            Self::MouthSmileRight => "MouthSmileRight",
            Self::MouthSmileLeft => "MouthSmileLeft",
            Self::MouthSadRight => "MouthSadRight",
            Self::MouthSadLeft => "MouthSadLeft",
        }
    }
}
